//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSend.WebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSend.WebApi.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason cannot be an empty string..
        /// </summary>
        internal static string BadRequest_WhiteSpaceReason {
            get {
                return ResourceManager.GetString("BadRequest_WhiteSpaceReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller&apos;s configuration must contain a formatter that supports the media type application/json..
        /// </summary>
        internal static string ConfigurationMustContainFormatter {
            get {
                return ResourceManager.GetString("ConfigurationMustContainFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message cannot be an empty string..
        /// </summary>
        internal static string ErrorResponse_WhiteSpaceMessage {
            get {
                return ResourceManager.GetString("ErrorResponse_WhiteSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource could not be found..
        /// </summary>
        internal static string NotFound_DefaultMessage {
            get {
                return ResourceManager.GetString("NotFound_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason cannot be an empty string..
        /// </summary>
        internal static string NotFound_WhiteSpaceReason {
            get {
                return ResourceManager.GetString("NotFound_WhiteSpaceReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request must have a request context..
        /// </summary>
        internal static string Request_RequestContextMustNotBeNull {
            get {
                return ResourceManager.GetString("Request_RequestContextMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization has been denied for this request..
        /// </summary>
        internal static string RequestNotAuthorized {
            get {
                return ResourceManager.GetString("RequestNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} must not be null..
        /// </summary>
        internal static string TypePropertyMustNotBeNull {
            get {
                return ResourceManager.GetString("TypePropertyMustNotBeNull", resourceCulture);
            }
        }
    }
}
