//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSend.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSend.Client.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status cannot be JSendStatus.Success..
        /// </summary>
        internal static string ErrorWithSuccessStatus {
            get {
                return ResourceManager.GetString("ErrorWithSuccessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the request..
        /// </summary>
        internal static string HttpClientExecutionError {
            get {
                return ResourceManager.GetString("HttpClientExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP response message could not be parsed into an instance of type &quot;{0}&quot;. Content:{1}{2}.
        /// </summary>
        internal static string ResponseParseError {
            get {
                return ResourceManager.GetString("ResponseParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP response had an empty body..
        /// </summary>
        internal static string ResponseWithoutContent {
            get {
                return ResourceManager.GetString("ResponseWithoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSend response was successful but did not contain any data..
        /// </summary>
        internal static string SuccessResponseWithoutData {
            get {
                return ResourceManager.GetString("SuccessResponseWithoutData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSend status does not indicate success: &quot;{0}&quot;..
        /// </summary>
        internal static string UnsuccessfulResponse {
            get {
                return ResourceManager.GetString("UnsuccessfulResponse", resourceCulture);
            }
        }
    }
}
